---
title: "CurveInterpreter v`r 0+round((27-4)/27,2)`"
# output:
#   prettydoc::html_pretty:
#     theme: architect
#     highlight: github
#     toc: yes
#     number_sections: yes
#     toc_depth: 4
output:
    html_document:
    code_folding: show
    toc: yes
    number_sections: yes
    toc_depth: 4
    theme: cerulean
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      knitr.svg.object = TRUE, 
                      out.width='50%',
                      fig.align = 'center'
                      )
options(digits = 2)
set.seed(13796163)
```

```{r}
set.seed(13796163)
library(tidyverse)
library(kableExtra)
library(coda)
library(nortest)
# library(knitr)
# library(DiagrammeR)
# library(pracma)
# library(janitor)
# library(seastests)
# library(DiagrammeR)
# library(prettydoc)
# library(aTSA)

alpha_global <- .05
results <- list()
theme_set(theme_classic())
if(!exists('DocumentType')){
  DocumentType <- 2
}
```

#  {.tabset .tabset-fade .tabset-pills}

## Estrutura

```{r cronograma, out.width='100%'}
source('Misc/diagrama.R')
diagram
```

```{r}
source('https://raw.githubusercontent.com/hbrpaulo/Misc/refs/heads/main/format_sig.R')
format_sig1 <- format_sig
format_sig <- Vectorize(format_sig)
source('Misc/example_creation.R')
source('scripts/distances_calculator.R')
source('scripts/fragmentation.R')

column <- 't_jus_ckp'
dff <- arrow::read_parquet('https://github.com/petrobras/3W/raw/refs/heads/main/dataset/0/WELL-00001_20170201010207.parquet') %>% 
  janitor::clean_names() %>% 
  rename('data_series' = column) %>%
  select(data_series)
```

```{r}
# Reduction of data size and creation of a fictional interval
janela <- 6001
w3 <- tibble(data_series = zoo::rollmean(dff$data_series, janela),
             reference_values = zoo::rollmedian(dff$data_series, janela),
             sd1 = zoo::rollapply(dff$data_series, width = janela, FUN = sd),
             reference_upper_bound = reference_values + sd1/2,
             reference_lower_bound = reference_values - sd1/2
)
```

```{r}
database <- fragmentation(distances_calculator(w3))
```

```{r tests_functions}
source('scripts/tests/trends_test.R')
source('scripts/tests/seasonalities_test.R')
source('scripts/tests/fragments_comparison_test.R')
```

```{r interpretations_functions}
source('scripts/interpretations/trends_interpretations.R')
source('scripts/interpretations/seasonalities_interpretations.R')
source('scripts/interpretations/fragments_comparison_interpretations.R')
```

```{r noref, results='asis'}
if(DocumentType >= 0){
  cat(knitr::asis_output(knitr::knit_child("rmd_noref.Rmd",
                                           quiet=TRUE, envir=environment())))
}
```

```{r punctual, results='asis'}
# database <- fragmentation(distances_calculator(example1))
database <- fragmentation(distances_calculator(w3))
if(DocumentType >= 1){
  cat(knitr::asis_output(knitr::knit_child("rmd_reference_punctual.Rmd",
                                           quiet=TRUE, envir=environment())))
}
```

```{r interval, results='asis'}
if(DocumentType == 2){
  cat(knitr::asis_output(knitr::knit_child("rmd_reference_interval.Rmd",
                                           quiet=TRUE, envir=environment())))
}
```
